### ISSUE TITLE
Issues with right clicking?

### ISSUE THREAD

**Issue by squeek502** [progwml6/HungerOverhaul#101]
From MCF:

> we have found a bug on our server running on native forge with infitech2v316 modpack without any changes.
If we have planted some e.g. carrots and then harvested it with right click, eating something or use of buckets is blocked now. Can you check this out please ? It seems to be fixed if we remove hunger overhaul but that should not be the target..

**Comment by squeek502** [comment]
Possible duplicate of #87, which still needs to be looked into more.

**Comment by usafphoenix** [comment]
using "right-click-to-harvest = true" along with "doDaylightCycle = false" or any mod that effectively freezes the game timer breaks all the things, i took a peak at the hungeroverhaul code awhile back and it's because there's some trickery/round-about-way of single-click-harvesting that's been done. 

disable the click to harvest, or temporarily set doDaylightCycle to true, and then back to false again to progress the game clock long enough to exit the hungeroverhaul loop.

**Comment by usafphoenix** [comment]
also, if you do one of the things, and it works, let us know. (i'm pretty sure either of those solutions will work)

**Comment by squeek502** [comment]
Should have actually been fixed by #104. Need to get a new version released with the fix included. Will try to do that soon.
