### ISSUE TITLE
Interaction with Biomes O'Plenty Crash

### ISSUE THREAD

**Issue by Tellik** [progwml6/HungerOverhaul#135]
Crash Log Here: http://pastebin.com/HhhN8LSy

Only mods present are Forge 2254, BOP 2162, Hunger Overhaul 1.1.0.jenkins111, and AppleCore 2.1.2

Edit: FYI - Biomes O Plenty does not support 1.10.2 and will not address issues from those versions.

**Comment by Rory-Lambert** [comment]
I got a similar 'updating neighbours' error from BoP check and drop block recently, after installing hungeroverhaul, which I believe to be the culprit. In my case it was a BoP plant rather than falling sand, but I think the issue is the same. After much testing, I was able to isolate hunger overhaul as the culprit. Fingers crossed it is a simple fix! 
[crash-2017-03-14_23.38.33-server.txt](https://github.com/progwml6/HungerOverhaul/files/843072/crash-2017-03-14_23.38.33-server.txt)

**Comment by AhHanie** [comment]
I was also having the same error as above with the same mod versions. Pastebin: http://pastebin.com/g6aXhRkw

**Comment by Tellik** [comment]
The downside to all of this is since BoP won't fix or update 1.10 versions, the only way for this to be fixed is on HungerOverhaul's end. It's also kinda sad that there aren't any other biomes mods other than BoP.

**Comment by alexbegt** [comment]
HungerOverhaul-1.10.2-1.1.0.jenkins113 has the updated fix to fix this issue.
