### ISSUE TITLE
Pmp and Hunger overhaul chrash

### ISSUE THREAD

**Issue by Rams59** [progwml6/HungerOverhaul#200]
The gamechrashes when i hover plant megapack fruits with a rendering issue

## Version Information
`Minecraft: `1.12.2
`Forge: `14.23.4.2749
`Mantle: `1.3.2.24
`Natura: `4.3.2.62
`Apple Core: `3.1.3
`Hunger Overhaul: `1.3.3.jenkins148

## Report Information
every time you hover the pmp fruits from the trees it chrashes and it seems to be an hunger overhaul issue. I know probably its not really made for pmp but i love the mod and would like to play with it

## Steps to Reproduce
Take a fruit from a pmp tree. go to menu and hover over it, Game freezes and chrashes

## Crash Log

[crash-2018-08-13_04.55.02-client.txt](https://github.com/progwml6/HungerOverhaul/files/2293559/crash-2018-08-13_04.55.02-client.txt)

**Comment by waefre1** [comment]
Would it be poor form to create a new issue if I have this same problem with Plant Mega Pack 1.12.1 on HO 1.3.3.jenkins148 and Applecore 3.2.0? I know that PMP and HO used to play wonderfully back together in 1.7.10, though there was a significant break where PMP's author stepped away from modding that doubtlessly complicated HO continuing to support it.

Also, this issue is likely related to #176, as Real World is a continuation/expansion of Plant Mega Pack and is done by the same author.
